### ISSUE TITLE
Windows: poco is sometimes not installed when built by poco_vendor

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/poco_vendor#22] opened 2018-06-26 19:40 UTC
The visible error was a failure in a downstream package to find Poco during CMake configuration. I checked for poco libraries in the poco_vendor install space and found only the poco_vendor resource files. When checking poco_vendor in the build space I did see an apparently successful build of poco in the poco_external_project_install directory.

Both @wjwwood and I experienced this at least once while testing from-source builds on Windows.

I don't have reliable reproduction steps since I only saw this the one time and as far as I know so did @wjwwood 

I deleted the poco_vendor directory from the install and build directories and resumed building my workspace and the subsequent poco_vendor build successfully built and installed poco.

**Comment by wjwwood** [comment] 2018-06-26 20:35
Yeah, I only saw it once as well. Went away when I deleted build and install so I could rebuild with the latest sources a day or so later.

**Comment by nuclearsandwich** [comment] 2018-06-28 01:08
over 4 attempts in fresh workspaces. Twice cloning all of ros2 via vcs and twice cloning just poco_vendor I couldn't get this to re-exhibit. I'm fine closing it as an odd fluke or leaving it open as an easy-to-find issue when the pool of people trying ROS 2 on completely fresh machines increases.

**Comment by wjwwood** [comment] 2018-06-28 01:10
I'd say just close it, and we can reopen if others report it. Users should find it through Google, and if not we'll just close as a duplicate of this.

**Closed as completed by wjwwood** 2018-06-28 01:10 UTC
Labels: bug
